<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="md2spchc" ignored="0" name="EdgeTest" tests="1" failures="1" timestamp="2023-08-25T18:44:48 IST" time="21.03" errors="0">
  <testcase name="ShopProduct" time="11.801" classname="TestCases.TC5_ShopProduct">
    <failure type="java.lang.AssertionError" message="Step1 - User is NOT logged in successfully expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step1 - User is NOT logged in successfully expected [true] but found [false]
at TestCases.TC5_ShopProduct.ShopProduct(TC5_ShopProduct.java:53)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ShopProduct -->
</testsuite> <!-- EdgeTest -->
